name: Publish
on:
  push:
    branches:
    - master
jobs:
  publish:
    name: Python ${{ matrix.python-version }} / Django ${{ matrix.django-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channels-version: [4.3.2]
        python-version: ['3.14']
        django-version: ['6.1.1']
    env:
      POETRY_VIRTUALENVS_CREATE: false
      UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
    steps:
    - uses: actions/checkout@v7.0.1
    - uses: actions/setup-python@v7.0.0
      with:
        python-version: ${{ matrix.python-version }}
    - run: python3 -m pip install --user uv
    - run: python3 -m pip install --upgrade setuptools pip celery daphne pytest-django
    - run: python3 -m pip install 'django==${{ matrix.django-version }}' 'channels==${{ matrix.channels-version }}' daphne
    - run: python3 -m pip install .
    - run: python3 -m demo_df_websockets migrate
    - run: python3 -m pytest -s --doctest-modules --doctest-glob=df_websockets/*.py --doctest-glob=df_websockets/**/*.py
    - run: python3 -m uv build
    - run: python3 -m uv publish
